### ISSUE TITLE
Taking screenshots with multiple threads on Wayland can cause the program to become frozen, and then return an error

### ISSUE THREAD

**Issue by FractalFir** [nashaofu/xcap#155]
While working on a tool that uses `xcap`, I have discovered `xcap` will sometimes get stuck trying to take screenshots on Wayland. After a while, ` Error("Screenshot failed or canceled")` will get returned. 

This example will hang every few runs on Wayland:

```rust
use xcap::Monitor;

fn normalized(filename: &str) -> String {
    filename
        .replace("|", "")
        .replace("\\", "")
        .replace(":", "")
        .replace("/", "")
}
fn make_screenshots() {
    println!("Preparing to take a screenshot!");
    let monitors = Monitor::all().unwrap();
    for monitor in monitors {
        monitor.capture_image().unwrap();
    }
    println!("Taken a screenshot!");
}
fn main() {
    let start = Instant::now();
        // This thread will sometimes hang on Wayland, and then `xcap` will return an error message.
    let handle = std::thread::spawn(|| {
        make_screenshots();
    });
    make_screenshots();

    handle.join();
}
```

I have run this problematic example under a debugger, and this is the backtrace of the hanging thread:

```
#0  0x00007ffff7d84e57 in __GI___select (nfds=5, readfds=0x7fffffffb860, writefds=0x7fffffffb7e0, exceptfds=0x7fffffffb760, timeout=0x7fffffffb750) at ../sysdeps/unix/sysv/linux/select.c:69
#1  0x000055555594001b in _dbus_poll (fds=0x7fffffffb954, n_fds=1, timeout_milliseconds=1000) at ./vendor/dbus/dbus/dbus-sysdeps-unix.c:3186
#2  0x0000555555960a61 in socket_do_iteration (transport=0x555555cb6f50, flags=6, timeout_milliseconds=1000) at ./vendor/dbus/dbus/dbus-transport-socket.c:1183
#3  0x0000555555958d44 in _dbus_transport_do_iteration (transport=0x555555cb6f50, flags=6, timeout_milliseconds=1000) at ./vendor/dbus/dbus/dbus-transport.c:1013
#4  0x00005555559434c3 in _dbus_connection_do_iteration_unlocked (connection=0x555555cb7bd0, pending=0x0, flags=6, timeout_milliseconds=1000) at ./vendor/dbus/dbus/dbus-connection.c:1227
#5  0x0000555555945e01 in _dbus_connection_read_write_dispatch (connection=0x555555cb7bd0, timeout_milliseconds=1000, dispatch=0) at ./vendor/dbus/dbus/dbus-connection.c:3705
#6  0x0000555555945ef5 in dbus_connection_read_write (connection=0x555555cb7bd0, timeout_milliseconds=1000) at ./vendor/dbus/dbus/dbus-connection.c:3805
#7  0x000055555590b9f4 in dbus::channel::ffichannel::Channel::read_write (self=0x7fffffffce38, timeout=...) at src/channel/ffichannel.rs:256
#8  0x000055555590bb6e in dbus::channel::ffichannel::Channel::blocking_pop_message (self=0x7fffffffce38, timeout=...) at src/channel/ffichannel.rs:288
#9  0x0000555555938638 in dbus::blocking::Connection::process (self=0x7fffffffce10, timeout=...) at src/blocking.rs:239
#10 0x0000555555811009 in xcap::platform::wayland_capture::org_freedesktop_portal_screenshot (conn=0x7fffffffce10, x=0, y=0, width=2560, height=1600) at src/linux/wayland_capture.rs:135
#11 0x00005555558125b6 in xcap::platform::wayland_capture::wayland_capture::{closure#0} () at src/linux/wayland_capture.rs:179
#12 0x0000555555830560 in core::result::Result<image::buffer_::ImageBuffer<image::color::Rgba<u8>, alloc::vec::Vec<u8, alloc::alloc::Global>>, xcap::error::XCapError>::or_else<image::buffer_::ImageBuffer<image::color::Rgba<u8>, alloc::vec::Vec<u8, alloc::alloc::Global>>, xcap::error::XCapError, xcap::error::XCapError, xcap::platform::wayland_capture::wayland_capture::{closure_env#0}> (self=..., op=...) at /rustc/fa724e5d8cbbdfbd1e53c4c656121af01b694406/library/core/src/result.rs:1409
#13 0x0000555555812548 in xcap::platform::wayland_capture::wayland_capture (impl_monitor=0x7fffffffd1d0) at src/linux/wayland_capture.rs:178
#14 0x000055555580fb7e in xcap::platform::capture::capture_monitor (impl_monitor=0x7fffffffd1d0) at src/linux/capture.rs:27
#15 0x00005555557cb176 in xcap::platform::impl_monitor::ImplMonitor::capture_image (self=0x7fffffffd1d0) at src/linux/impl_monitor.rs:237
#16 0x0000555555783076 in xcap::monitor::Monitor::capture_image (self=0x7fffffffd1d0) at src/monitor.rs:79
#17 0x000055555576c86d in xcap_test::make_screenshots () at src/main.rs:15
#18 0x000055555576ca48 in xcap_test::main () at src/main.rs:24
```

I am running this on Wayland Gnome 46, Fedora 40, x86_64, but I have seen other peopele encounter this issue on other architectures.

**Comment by FractalFir** [comment]
Fixed in my PR.
